### ISSUE TITLE
方便请教一下问题吗？

### ISSUE THREAD

**Issue by lujiqing** [guozeyu0827/IGZO_model#1]
哈喽，你好，能给个联系方式，请教一下问题吗？

**Comment by guozeyu0827** [comment]
***@***.***。 欢迎讨论！

2024-07-27 02:04:49"lujiqing" ***@***.***>写道：

哈喽，你好，能给个联系方式，请教一下问题吗？

**Comment by lujiqing** [comment]
方便加微信吗？19818933792
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年7月29日 10:05
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [guozeyu0827/IGZO_model] 方便请教一下问题吗？ (Issue #1)
        
      
    
  

***@***.***。 欢迎讨论！

2024-07-27 02:04:49"lujiqing" ***@***.***>写道：

哈喽，你好，能给个联系方式，请教一下问题吗？

**Comment by guozeyu0827** [comment]
加您微信了


发件人：lujiqing ***@***.***>
发送日期：2024-07-29 12:19:25
收件人：guozeyu0827/IGZO_model ***@***.***>
抄送人：
主 题：Re: [guozeyu0827/IGZO_model] 方便请教一下问题吗？ (Issue #1)






方便加微信吗？19818933792


---- 回复的原邮件 ----





发件人


***@***.***>





发送日期


2024年7月29日 10:05




收件人




***@***.***>






抄送人



***@***.***>
,


***@***.***>






主题


Re: [guozeyu0827/IGZO_model] 方便请教一下问题吗？ (Issue #1)





***@***.***。 欢迎讨论！

2024-07-27 02:04:49"lujiqing" ***@***.***>写道：

哈喽，你好，能给个联系方式，请教一下问题吗？
